### ISSUE TITLE
Video Tutorials are Private

### ISSUE THREAD

**Issue by nnvpgh** [grasshopper3d/GrasshopperDocsSite#16]
Hello; I'm trying to access the videos on the bottom of the page: 
https://grasshopperdocs.com/addons/kuka-prc-pro.html

But it looks like the files are private; is there a way to fix this? 

Kindly get back to me on nickynaimeh@gmail.com if this issue is solved

Thank you in advance 
Nicky

<img width="1378" alt="Screen Shot 2022-10-11 at 8 32 10 AM" src="https://user-images.githubusercontent.com/101062376/195004694-3d741286-d285-40be-96ea-b15e29a0faf0.png">

**Comment by robinrodricks** [comment]
We only link to public videos, we do not have any more info than that.
