### ISSUE TITLE
Raccoon download link

### ISSUE THREAD

**Issue by Quentinmatin** [grasshopper3d/GrasshopperDocsSite#17]
Hello, 

The Raccoon download link seems to be not wroking. And i do not find these plug-in anywhere else.

**Comment by robinrodricks** [comment]
Hi,

You need Rhino 7+ and it appears using the Rhino Package Manager.

![image](https://user-images.githubusercontent.com/6797866/216301140-ef913662-cfa4-4baa-a5fa-736b97fbdb11.png)

![image](https://user-images.githubusercontent.com/6797866/216301121-e3d54878-86b3-4cd9-8558-cc3e9168ccba.png)

**Comment by Quentinmatin** [comment]
Hi,

Tanks for the quick reply, I'll look into that.

Have a good day

Le jeu. 2 févr. 2023 à 11:33, Robin Rodricks ***@***.***> a
écrit :
