### ISSUE TITLE
Fennec author name correction

### ISSUE THREAD

**Issue by seghier** [grasshopper3d/GrasshopperDocsSite#20]
Hello
Thank you for adding Fennec to the website
Just a small error in my name, it's **Seghier** not Segheir :)

![image](https://github.com/grasshopper3d/GrasshopperDocsSite/assets/6026588/bb44e807-7806-4347-9ac5-d871741ebd96)

And in the bottom of the page is `Co-created by` related to the website or the addon? Because i am the only developer of the addon

![image](https://github.com/grasshopper3d/GrasshopperDocsSite/assets/6026588/0aac5425-015c-4d41-8911-a8424fbc44a3)

And there are many videos tutorials about Fennec and other addons in parametrichouse website

https://parametrichouse.com/

**Comment by robinrodricks** [comment]
Sure I will fix that. Bottom is the site credits, not addon credits :)

If you send me a list of video links on youtube we can display those.

**Comment by robinrodricks** [comment]
Its done.
