### ISSUE TITLE
Don't list components whose Exposure is hidden

### ISSUE THREAD

**Issue by karakasa** [grasshopper3d/GrasshopperDocsSite#5]
### Brief Description
Hidden components are listed in the docs, which they shouldn't be.

### How to replicate
For example, you can see the "Internal" tab in the [Pancake Docs](https://grasshopperdocs.com/addons/pancake.html)

In the code, it is defined as such:
`public override GH_Exposure Exposure => GH_Exposure.hidden;`

### Expected behavior
They shouldn't be listed or at least they'd be listed separately, as it may cause confusion to end users.

**Comment by robinrodricks** [comment]
I will work on this.

**Comment by robinrodricks** [comment]
Fixed in pancake and all the other addons as well!

https://grasshopperdocs.com/addons/pancake.html
