### ISSUE TITLE
Many Grasshopper core components not displayed

### ISSUE THREAD

**Issue by fstwn** [grasshopper3d/GrasshopperDocsSite#7]
Lots of core components are not displayed in the docs at all, although they seem to be there in the repo. Is there maybe a bug with other (addon) components or categories having the same name?
For example: Pufferfish has a "Domain" category which is correctly displayed. Grasshopper Maths also should have a "Domain" category but it is not properly displayed.

As far as I could tell there are missing components in maths, params, sets

![Maths components missing](https://user-images.githubusercontent.com/13224396/79369271-facbe880-7f50-11ea-9b76-7737e49aad69.PNG)

**Comment by fstwn** [comment]
PS: HMU if I could be of help. I would love to contribute by fixing it myself but don't really know where to start looking.

**Comment by robinrodricks** [comment]
Can you tell me the names of components that are missing. I have to check on a compo by compo basis. Many were recently removed as they were internally marked "hidden" or "obsolete" as many authors requested for this.

**Comment by fstwn** [comment]
It's quite a lot of comps so I'll start with the "Math" section and will continue from there

### Math Category
**Subcategory: Domain**
- Construct Domain
- Deconstruct Domain
- Bounds
- Consecutive Domains
- Divide Domain
- Find Domain
- Includes
- Remap Numbers
- Construct Domain² (from 4 numbers)
- Construct Domain² (from 2 domains)
- Deconstruct Domain² (into 4 numbers)
- Deconstruct Domain² (into 2 domains)
- Bounds 2D
- Divide Domain²

**Subcategory: Matrix**
- Construct Matrix
- Deconstruct Matrix
- Display Matrix
- Invert Matrix
- Transpose Matrix
- Swap Columns
- Swap Rows

I'll continue the list later when I have some more procrastination time ;)
In the meantime: If there's any way to tell me which files to check and for what to look, I'll gladly fix some stuff myself and contribute via pull requests. Just an offer, I don't want to be obtrusive ;)

**Comment by robinrodricks** [comment]
Thanks for this. I'll investigate and let you know. Well thanks but the files are not created by hand. Its generated by a tool, and the tool is currently closed source.

You don't need to list any more. Thanks.

**Comment by fstwn** [comment]
Alright, thank you for taking this on and your information! :)

**Comment by robinrodricks** [comment]
All are fixed now.

- Consecutive Domains - https://grasshopperdocs.com/components/grasshoppermaths/consecutiveDomains.html
- Construct Domain - https://grasshopperdocs.com/components/grasshoppermaths/constructDomain.html
- Display Matrix - https://grasshopperdocs.com/components/grasshoppermaths/displayMatrix.html
- Transpose Matrix - https://grasshopperdocs.com/components/grasshoppermaths/transposeMatrix.html
