### ISSUE TITLE
Input and Output tables list Parameters twice

### ISSUE THREAD

**Issue by worbit** [grasshopper3d/GrasshopperDocsSite#8]
for some of the components, the two tables **Input** and **Output** correctly list each parameter only once, e.g. Sphere: https://grasshopperdocs.com/components/axolotl/sphere.html

for some (most) other components, all the Parameters in the two tables are listed twice, e.g. Pipe: https://grasshopperdocs.com/components/axolotl/pipe.html

If one of the Parameters is of type **Generic**, it is listed once as **Generic Data** and once as **Generic**.

**Comment by robinrodricks** [comment]
Fixed. Thanks for reporting!

You'll see the update in a few hours.
