### ISSUE TITLE
Search box

### ISSUE THREAD

**Issue by em99** [grasshopper3d/GrasshopperDocsSite#9]
please, can you add a search box?

![serach box](https://user-images.githubusercontent.com/31850380/83871187-eb3a7600-a72f-11ea-84fe-8ceea6be3cdb.png)

**Comment by robinrodricks** [comment]
Good idea!

**Comment by robinrodricks** [comment]
Search bar has been added to the main menu!

![image](https://user-images.githubusercontent.com/6797866/159001371-bee15fa2-a4b1-4c9f-ab58-e97586e91ce9.png)

**Comment by em99** [comment]
thank you so much!!!!!
